-- Idempotent contract alignment for project glasazanchaycnkklybw.
alter table public.data_sources add column if not exists source_key text;
alter table public.data_sources add column if not exists provider text;
alter table public.data_sources add column if not exists status text;
alter table public.data_sources add column if not exists last_seen_at timestamptz;
alter table public.data_sources add column if not exists latency_ms integer;
alter table public.data_sources add column if not exists updated_at timestamptz;
create unique index if not exists data_sources_source_key_uidx on public.data_sources(source_key);
alter table public.market_feed_latest add column if not exists instrument text;
alter table public.market_feed_latest add column if not exists provider text;
alter table public.market_feed_latest add column if not exists source text;
alter table public.market_feed_latest add column if not exists status text;
alter table public.market_feed_latest add column if not exists observed_at timestamptz;
alter table public.market_feed_latest add column if not exists received_at timestamptz;
alter table public.market_feed_latest add column if not exists price double precision;
alter table public.market_feed_latest add column if not exists latency_ms integer;
alter table public.market_feed_latest add column if not exists payload jsonb;
create unique index if not exists market_feed_latest_instrument_uidx on public.market_feed_latest(instrument);
alter table public.market_bars add column if not exists instrument text;
alter table public.market_bars add column if not exists contract text;
alter table public.market_bars add column if not exists timeframe text;
alter table public.market_bars add column if not exists bar_time timestamptz;
alter table public.market_bars add column if not exists open double precision;
alter table public.market_bars add column if not exists high double precision;
alter table public.market_bars add column if not exists low double precision;
alter table public.market_bars add column if not exists close double precision;
alter table public.market_bars add column if not exists volume bigint;
alter table public.market_bars add column if not exists bid_volume bigint;
alter table public.market_bars add column if not exists ask_volume bigint;
alter table public.market_bars add column if not exists delta bigint;
alter table public.market_bars add column if not exists delta_percent double precision;
alter table public.market_bars add column if not exists source text;
alter table public.market_bars add column if not exists received_at timestamptz;
create unique index if not exists market_bars_identity_uidx on public.market_bars(instrument, bar_time, timeframe);
alter table public.orderflow_snapshots add column if not exists instrument text;
alter table public.orderflow_snapshots add column if not exists contract text;
alter table public.orderflow_snapshots add column if not exists observed_at timestamptz;
alter table public.orderflow_snapshots add column if not exists bar_time timestamptz;
alter table public.orderflow_snapshots add column if not exists total_volume bigint;
alter table public.orderflow_snapshots add column if not exists bid_volume bigint;
alter table public.orderflow_snapshots add column if not exists ask_volume bigint;
alter table public.orderflow_snapshots add column if not exists bar_delta bigint;
alter table public.orderflow_snapshots add column if not exists cumulative_delta bigint;
alter table public.orderflow_snapshots add column if not exists delta_percent double precision;
alter table public.orderflow_snapshots add column if not exists source text;
alter table public.orderflow_snapshots add column if not exists raw_metrics jsonb;
alter table public.data_sources enable row level security;
alter table public.market_feed_latest enable row level security;
alter table public.market_bars enable row level security;
alter table public.orderflow_snapshots enable row level security;
alter table public.engine_snapshots enable row level security;
