'use client';
import LiveFeed from './LiveFeed';
import { useState } from 'react';
import useMarketContext from './useMarketContext';
import {Activity, Bell, ChevronRight, CircleDollarSign, Gauge, Gem, Landmark, Menu, Radio, Settings2, ShieldAlert, TrendingDown, TrendingUp, Waves, Zap} from 'lucide-react';
const usd=['EUR/USD','USD/JPY','USD/CHF','USD/CAD','GBP/USD','AUD/USD'];
const eur=['EUR/USD','EUR/GBP','EUR/JPY'];
function FxPair({symbol, data, now}) {
  const q = data?.quotes?.find(q => q.symbol === symbol);
  const status = !q || q.price === null ? 'SIN DATOS' : q.status !== 'fresh' || now - Date.parse(q.asOf) > 1800000 || now - Date.parse(data.fetchedAt) > 1800000 ? 'ANTIGUO' : 'REAL · CACHÉ';
  return <Pair p={[symbol, status + (q?.asOf ? ' · ' + new Date(q.asOf).toLocaleString() : ''), q?.price != null ? q.price.toFixed(symbol.endsWith('JPY') ? 3 : 5) : '—', q?.change != null ? (q.change > 0 ? '+' : '') + q.change.toFixed(2) + '%' : '—', q?.change > 0 ? 'up' : q?.change < 0 ? 'down' : '']} />;
}
const label = value => value == null ? 'SIN DATOS' : value.score > 50 ? 'STRONG' : value.score < 50 ? 'WEAK' : 'NEUTRAL';
const markets=[['GC','Gold','2,648.3','+0.64%'],['CL','WTI Oil','69.42','-0.37%'],['US 2Y','Yield','3.61%','-4.2bp'],['US 10Y','Yield','4.03%','-3.1bp'],['ES','S&P 500','6,121','+0.28%'],['VIX','Volatility','15.8','-2.1%']];
function Pill({children,tone='neutral'}){return <span className={'pill '+tone}>{children}</span>}
function Pair({p}){return <div className="pair"><div><b>{p[0]}</b><span>{p[1]}</span></div><div className="pairR"><strong>{p[2]}</strong><em className={p[4]}>{p[3]}</em></div></div>}
function Meter({label,value,sub,tone}){return <div className="meter"><div className="meterTop"><span>{label}</span><b>{value}</b></div><div className="track"><i className={tone} style={{width:value === '—' ? '0%' : value}}/></div><small>{sub}</small></div>}
export default function Page(){const [token,setToken]=useState(''); const {data,strength,now}=useMarketContext(token); return <main>
<header><div className="brand"><div className="logo"><Waves/></div><div><b>6E MARKET COMMAND</b><span>EUR/USD Intermarket Intelligence</span></div></div><div className="session"><Radio size={15}/><span>FX CONTEXT</span><b>20 MIN</b></div><div className="headicons"><Bell/><Settings2/><div className="avatar">VZ</div></div></header>
<LiveFeed onTokenChange={setToken}/><div className="demo-label">FX: Twelve Data · actualización máxima cada 20 minutos. DXY, tasas, otros mercados y señales avanzadas: DEMO. El 6E real está en el panel NinjaTrader.</div>
<div className="ticker"><span>EUR/USD <b>{data?.quotes?.find(q=>q.symbol==='EUR/USD')?.price?.toFixed(5) || '—'}</b> <i>Ver antigüedad en EUR Engine</i></span><span>DXY <b>DEMO</b></span><span>GC <b>DEMO</b></span><span>US2Y <b>DEMO</b></span><span>US10Y <b>DEMO</b></span><span>CL <b>DEMO</b></span></div>
<section className="hero"><div><Pill>CONTEXTO FX · SIN SEÑAL DE ENTRADA</Pill><h1>EUR <span>{label(strength?.EUR)}</span> · USD <span className="weak">{label(strength?.USD)}</span></h1><p>Amplitud direccional frente al cierre previo: USD con 6 pares y EUR con 3. No incluye tasas ni order flow. {data?.fetchedAt ? 'Última consulta: '+new Date(data.fetchedAt).toLocaleString()+'.' : 'Conecta con tu clave de lectura para consultar FX.'} {data?.reason ? 'Actualización pendiente: '+({not_configured:'falta configurar Twelve Data',storage_unavailable:'almacenamiento no disponible',daily_budget:'presupuesto diario agotado',cooldown:'caché protegida',provider_or_cache_unavailable:'proveedor o caché no disponible'}[data.reason] || 'sin datos')+'.' : ''}</p></div><div className="score"><div><small>CONFLUENCE SCORE</small><strong>—</strong><span>Pendiente de integración completa</span></div></div></section>
<section className="gridTop"><div className="card"><div className="ct"><CircleDollarSign/><div><b>USD ENGINE</b><span>Dollar breadth</span></div><Pill>{label(strength?.USD)}</Pill></div><Meter label="USD Strength" value={strength?.USD ? strength.USD.score+'%' : '—'} sub="6 pares · positivos / total · planos cuentan ½" tone="redbar"/>{usd.map(symbol=><FxPair symbol={symbol} data={data} now={now} key={symbol}/>)}<Pair p={['DXY · DEMO','USD Index · no conectado','104.18','-0.34%','down']}/></div>
<div className="card"><div className="ct"><Landmark/><div><b>EUR ENGINE</b><span>Euro breadth</span></div><Pill>{label(strength?.EUR)}</Pill></div><Meter label="EUR Strength" value={strength?.EUR ? strength.EUR.score+'%' : '—'} sub="3 pares · positivos / total · planos cuentan ½" tone="greenbar"/>{eur.map(symbol=><FxPair symbol={symbol} data={data} now={now} key={symbol}/>)}{['EURCHF','EURCAD','EURAUD'].map(symbol=><Pair p={[symbol+' · DEMO','No conectado · excluido de Strength','—','—','']} key={symbol}/>)}</div>
<div className="card rates"><div className="ct"><Activity/><div><b>RATES ENGINE · DEMO</b><span>US vs Eurozone</span></div><Pill tone="green">EUR +</Pill></div><div className="rateHero"><small>US 2Y − DE 2Y SPREAD</small><b>+1.58%</b><em>▼ 6.4 bp today</em></div><div className="rateRow"><span>US 2Y</span><b>3.61%</b><i>▼ 4.2bp</i></div><div className="rateRow"><span>DE 2Y</span><b>2.03%</b><i className="up">▲ 2.2bp</i></div><div className="note"><TrendingUp/> Spread compression supports EUR relative to USD.</div><div className="banks"><div><span>FED EXPECTATION</span><b>DOVISH</b><small>Rates repricing lower</small></div><div><span>ECB EXPECTATION</span><b>NEUTRAL</b><small>Less dovish vs Fed</small></div></div></div></section>
<section className="lower"><div className="card market"><div className="ct"><Gem/><div><b>INTERMARKET · DEMO</b><span>Commodities & risk</span></div><Pill tone="green">CONFIRMING</Pill></div><div className="marketgrid">{markets.map((m,i)=><div key={i}><span>{m[0]} · {m[1]} · DEMO</span><b>{m[2]}</b><i className={m[3].startsWith('+')?'up':'down'}>{m[3]}</i></div>)}</div><div className="signals"><span><b>GOLD ↑ + DXY ↓</b> USD weakness confirmation</span><span><b>YIELDS ↓</b> Supportive for EURUSD</span><span><b>VIX ↓</b> No strong risk-off conflict</span></div></div>
<div className="card flow"><div className="ct"><Gauge/><div><b>6E ORDER FLOW · DEMO</b><span>Execution layer</span></div><Pill tone="green">BUYERS</Pill></div><div className="flowgrid"><div><span>DELTA</span><b>+3,842</b><small>Positive</small></div><div><span>CUM. DELTA</span><b>+12.6K</b><small>Rising</small></div><div><span>VWAP</span><b>1.09488</b><small>Price above</small></div><div><span>POC</span><b>1.09542</b><small>Accepted above</small></div></div><div className="event"><ShieldAlert/><div><b>Liquidity sweep detected</b><span>Session low swept → sellers absorbed → price reclaimed VWAP.</span></div><ChevronRight/></div><div className="checks"><span>✓ Buy imbalance</span><span>✓ Delta divergence</span><span>✓ Absorption</span><span>✓ VWAP reclaim</span></div></div></section>
<section className="decision"><div><span className="pulse"></span><div><small>CONTEXTO PARCIAL · SIN RECOMENDACIÓN</small><b>6E · EURUSD</b></div></div><div className="logic"><span>USD <b>{label(strength?.USD)}</b></span><i>+</i><span>EUR <b>{label(strength?.EUR)}</b></span><i>+</i><span>RATES <b>DEMO</b></span></div><div className="bias"><small>BIAS OPERATIVO</small><b>—</b><span>Pendiente de datos completos</span></div></section><footer><span><Activity size={14}/> NinjaTrader: panel superior. FX: Twelve Data con caché. Bloques DEMO excluidos de Strength.</span><span>Designed for 6E / EURUSD</span></footer>
</main>}


