'use client';
import LiveFeed from './LiveFeed';
import { useState } from 'react';
import useMarketContext from './useMarketContext';
import {Activity, Bell, ChevronRight, CircleDollarSign, Gauge, Gem, Landmark, Menu, Radio, Settings2, ShieldAlert, TrendingDown, TrendingUp, Waves, Zap} from 'lucide-react';
const usd=['EUR/USD','GBP/USD','AUD/USD','NZD/USD','USD/JPY','USD/CHF','USD/CAD'];
const eur=['EUR/USD','EUR/GBP','EUR/JPY','EUR/CHF','EUR/CAD','EUR/AUD','EUR/NZD'];
function FxPair({symbol, data, now, period}) {
  const q = data?.quotes?.find(q => q.symbol === symbol);
  const change = q?.changes?.[period];
  const maxAge = (data?.maxAgeSeconds || 1800) * 1000;
  const tickAge = q?.tickAt ? Math.max(0,Math.floor((now-Date.parse(q.tickAt))/1000)) : null;
  const status = !q || q.price === null ? 'SIN DATOS' : q.status !== 'fresh' || now - Date.parse(q.tickAt || q.asOf) > maxAge || now - Date.parse(data.fetchedAt) > maxAge ? 'ANTIGUO' : data?.source === 'MT5 / FOREX.com' ? (data.mode === 'live' ? 'LIVE MT5 · BID' : 'DEMO MT5 · BID') : 'REAL · CIERRE 5 MIN';
  return <Pair p={[symbol, status + (tickAge !== null ? ' · tick hace '+tickAge+' s · Ask '+q.ask?.toFixed(symbol.endsWith('JPY') ? 3 : 5) : '') + (q?.asOf ? ' · ' + new Date(q.asOf).toLocaleString() : ''), q?.price != null ? q.price.toFixed(symbol.endsWith('JPY') ? 3 : 5) : '—', change != null ? (change > 0 ? '+' : '') + change.toFixed(3) + '%' : '—', change > 0 ? 'up' : change < 0 ? 'down' : '']} />;
}
const periodLabels = {'15m':'15 min','1h':'1 hora',day:'Día UTC'};
const pct = value => Number.isFinite(value) ? (value > 0 ? '+' : '') + value.toFixed(3) + '%' : '—';
function StrengthDetail({value}) {return <p className="feedmessage">Cambio medio orientado: <b>{pct(value?.meanChange)}</b><br/>{value ? `${value.rising} positivos · ${value.neutral} neutrales · ${value.falling} negativos` : 'Sin cobertura completa para este periodo.'}</p>}
const label = value => value == null ? 'SIN DATOS' : value.score > 50 ? 'STRONG' : value.score < 50 ? 'WEAK' : 'NEUTRAL';
const markets=[['GC','Gold','2,648.3','+0.64%'],['CL','WTI Oil','69.42','-0.37%'],['US 2Y','Yield','3.61%','-4.2bp'],['US 10Y','Yield','4.03%','-3.1bp'],['ES','S&P 500','6,121','+0.28%'],['VIX','Volatility','15.8','-2.1%']];
function Pill({children,tone='neutral'}){return <span className={'pill '+tone}>{children}</span>}
function Pair({p}){return <div className="pair"><div><b>{p[0]}</b><span>{p[1]}</span></div><div className="pairR"><strong>{p[2]}</strong><em className={p[4]}>{p[3]}</em></div></div>}
function Meter({label,value,sub,tone}){return <div className="meter"><div className="meterTop"><span>{label}</span><b>{value}</b></div><div className="track"><i className={tone} style={{width:value === '—' ? '0%' : value}}/></div><small>{sub}</small></div>}
export default function Page(){const [token,setToken]=useState(''); const [period,setPeriod]=useState('1h'); const {data,strength,now}=useMarketContext(token,period); const mt5=data?.source==='MT5 / FOREX.com'; const dxy=data?.dxy; const dxyChange=dxy?.changes?.[period]; const dxyLive=dxy?.status==='fresh'; return <main>
<header><div className="brand"><div className="logo"><Waves/></div><div><b>6E MARKET COMMAND</b><span>EUR/USD Intermarket Intelligence</span></div></div><div className="session"><Radio size={15}/><span>FX CONTEXT</span><b>{mt5 ? "OBJETIVO 1 S" : data ? "20 MIN" : "—"}</b></div><div className="headicons"><Bell/><Settings2/><div className="avatar">VZ</div></div></header>
<LiveFeed onTokenChange={setToken}/><div className="demo-label">{mt5 ? "FX: MT5 / FOREX.com · envío y consulta objetivo 1 segundo · "+(data.mode === "live" ? "CUENTA LIVE" : data.mode === "demo" ? "CUENTA DEMO" : "ESPERANDO CONECTOR") : data ? "FX: Twelve Data · caché 20 minutos" : "FX: conecta para comprobar la fuente"}. DXY: {dxyLive ? "LIVE MT5" : "UNAVAILABLE"}. Tasas, otros mercados y señales avanzadas: DEMO. El 6E real está en el panel NinjaTrader.</div>
<div className="ticker"><span>EUR/USD <b>{data?.quotes?.find(q=>q.symbol==='EUR/USD')?.price?.toFixed(5) || '—'}</b> <i>Ver antigüedad en EUR Engine</i></span><span>DXY <b>{dxyLive ? dxy.price?.toFixed(3) : 'UNAVAILABLE'}</b></span><span>GC <b>DEMO</b></span><span>US2Y <b>DEMO</b></span><span>US10Y <b>DEMO</b></span><span>CL <b>DEMO</b></span></div>
<section className="hero"><div><Pill>CONTEXTO FX · {periodLabels[period]} · SIN SEÑAL DE ENTRADA</Pill><h1>EUR <span className={strength?.EUR?.score > 50 ? "up" : strength?.EUR?.score < 50 ? "down" : "neutral-text"}>{label(strength?.EUR)}</span> · USD <span className={strength?.USD?.score > 50 ? "up" : strength?.USD?.score < 50 ? "down" : "neutral-text"}>{label(strength?.USD)}</span></h1><p>Amplitud de {periodLabels[period]}: {mt5 ? "USD con 7 pares, USD ex-EUR con 6 y EUR con 7" : "USD con 6 pares y EUR con 3"}. {mt5 ? "Bid actual frente a cierres históricos M1; ventanas 15 min y 1 h ancladas al minuto" : "Cambios entre cierres de velas de 5 min"}; neutral entre −0,01% y +0,01%. No incluye tasas ni order flow. {data?.fetchedAt ? 'Última consulta: '+new Date(data.fetchedAt).toLocaleString()+'.' : (token ? 'Esperando la primera consulta del nuevo contexto.' : 'Conecta con tu clave de lectura para consultar FX.')} {data?.reason ? 'Actualización pendiente: '+({waiting_mt5:'esperando el primer envío de MT5',mt5_disconnected:'terminal MT5 desconectado',not_configured:'falta configurar Twelve Data',storage_unavailable:'almacenamiento no disponible',daily_budget:'presupuesto diario agotado',cooldown:'caché protegida',provider_or_cache_unavailable:'proveedor o caché no disponible'}[data.reason] || 'sin datos')+'.' : ''}</p></div><div className="score"><div><small>CONFLUENCE SCORE</small><strong>—</strong><span>Pendiente de integración completa</span></div></div></section>
<section className="period-controls" aria-label="Periodo de Strength"><div>{Object.entries(periodLabels).map(([key,name])=><button key={key} aria-pressed={period===key} onClick={()=>setPeriod(key)}>{name}</button>)}</div><p>Desde {data?.quotes?.find(q=>q.references?.[period])?.references?.[period] ? new Date(data.quotes.find(q=>q.references?.[period]).references[period]).toLocaleString() : '—'} hasta {data?.quotes?.find(q=>q.asOf)?.asOf ? new Date(data.quotes.find(q=>q.asOf).asOf).toLocaleString() : '—'} · Horas mostradas en tu zona local. Día UTC comienza a las 00:00 UTC. {mt5 ? "Lectura objetivo 1 s, sujeta a ticks y latencia. Sin datos nuevos no se inventan cambios." : "Refresco cada 20 min."} Cambiar la vista no consulta al proveedor.</p></section><section className="gridTop"><div className="card"><div className="ct"><CircleDollarSign/><div><b>USD ENGINE</b><span>Dollar breadth</span></div><Pill>{label(strength?.USD)}</Pill></div><Meter label={"USD Strength · "+periodLabels[period]} value={strength?.USD ? strength.USD.score+'%' : '—'} sub="Amplitud · neutral ±0,01% · no es probabilidad" tone="redbar"/><StrengthDetail value={strength?.USD}/><Meter label={"USD ex-EUR · "+periodLabels[period]} value={strength?.USD_EX_EUR ? strength.USD_EX_EUR.score+'%' : '—'} sub={label(strength?.USD_EX_EUR)+" · excluye EUR/USD"} tone="redbar"/>{usd.map(symbol=><FxPair symbol={symbol} data={data} now={now} period={period} key={symbol}/>)}<Pair p={dxyLive ? ['DXY · LIVE MT5','USD Index · '+periodLabels[period],dxy.price?.toFixed(3) || '—',dxyChange == null ? '—' : (dxyChange>0?'+':'')+dxyChange.toFixed(3)+'%',dxyChange>0?'up':dxyChange<0?'down':''] : ['DXY · UNAVAILABLE','Símbolo MT5 no configurado o antiguo','—','—','']}/></div>
<div className="card"><div className="ct"><Landmark/><div><b>EUR ENGINE</b><span>Euro breadth</span></div><Pill>{label(strength?.EUR)}</Pill></div><Meter label={"EUR Strength · "+periodLabels[period]} value={strength?.EUR ? strength.EUR.score+'%' : '—'} sub="Amplitud · neutral ±0,01% · no es probabilidad" tone="greenbar"/><StrengthDetail value={strength?.EUR}/>{eur.map(symbol=><FxPair symbol={symbol} data={data} now={now} period={period} key={symbol}/>)}</div>
<div className="card rates"><div className="ct"><Activity/><div><b>RATES ENGINE · DEMO</b><span>US vs Eurozone</span></div><Pill tone="green">EUR +</Pill></div><div className="rateHero"><small>US 2Y − DE 2Y SPREAD</small><b>+1.58%</b><em>▼ 6.4 bp today</em></div><div className="rateRow"><span>US 2Y</span><b>3.61%</b><i>▼ 4.2bp</i></div><div className="rateRow"><span>DE 2Y</span><b>2.03%</b><i className="up">▲ 2.2bp</i></div><div className="note"><TrendingUp/> Spread compression supports EUR relative to USD.</div><div className="banks"><div><span>FED EXPECTATION</span><b>DOVISH</b><small>Rates repricing lower</small></div><div><span>ECB EXPECTATION</span><b>NEUTRAL</b><small>Less dovish vs Fed</small></div></div></div></section>
<section className="lower"><div className="card market"><div className="ct"><Gem/><div><b>INTERMARKET · DEMO</b><span>Commodities & risk</span></div><Pill tone="green">CONFIRMING</Pill></div><div className="marketgrid">{markets.map((m,i)=><div key={i}><span>{m[0]} · {m[1]} · DEMO</span><b>{m[2]}</b><i className={m[3].startsWith('+')?'up':'down'}>{m[3]}</i></div>)}</div><div className="signals"><span><b>GOLD ↑ + DXY ↓</b> USD weakness confirmation</span><span><b>YIELDS ↓</b> Supportive for EURUSD</span><span><b>VIX ↓</b> No strong risk-off conflict</span></div></div>
<div className="card flow"><div className="ct"><Gauge/><div><b>6E ORDER FLOW · DEMO</b><span>Execution layer</span></div><Pill tone="green">BUYERS</Pill></div><div className="flowgrid"><div><span>DELTA</span><b>+3,842</b><small>Positive</small></div><div><span>CUM. DELTA</span><b>+12.6K</b><small>Rising</small></div><div><span>VWAP</span><b>1.09488</b><small>Price above</small></div><div><span>POC</span><b>1.09542</b><small>Accepted above</small></div></div><div className="event"><ShieldAlert/><div><b>Liquidity sweep detected</b><span>Session low swept → sellers absorbed → price reclaimed VWAP.</span></div><ChevronRight/></div><div className="checks"><span>✓ Buy imbalance</span><span>✓ Delta divergence</span><span>✓ Absorption</span><span>✓ VWAP reclaim</span></div></div></section>
<section className="decision"><div><span className="pulse"></span><div><small>CONTEXTO PARCIAL · SIN RECOMENDACIÓN</small><b>6E · EURUSD</b></div></div><div className="logic"><span>USD <b>{label(strength?.USD)}</b></span><i>+</i><span>EUR <b>{label(strength?.EUR)}</b></span><i>+</i><span>RATES <b>DEMO</b></span></div><div className="bias"><small>BIAS OPERATIVO</small><b>—</b><span>Pendiente de datos completos</span></div></section><footer><span><Activity size={14}/> NinjaTrader: panel superior. FX: {mt5 ? "MT5 / FOREX.com" : "Twelve Data con caché"}. Bloques DEMO excluidos de Strength.</span><span>Designed for 6E / EURUSD</span></footer>
</main>}



